feedhenry-raincatcher/raincatcher-demo-cloud

.travis.yml
README.md

Adding Travis CI for Node 0.10 and 4.4.2
**TRAVIS NEEDS TO BE ENABLED**

Travis updates; Node4 added

---

package.json
scripts/preinstall.sh

before_install with node-gyp

---

scripts/preinstall.sh

@matzew @odra Could you review and merge please ?

add global flag for node-gyp

---

.gitignore
npm-shrinkwrap.json
package.json

fh-mbaas-api update to 5.13.9
@nialldonnellyfh

Update fh-mbaas-api to version 5.13.9

---

lib/app.js

This change adds a middleware function that will verify the session added by requests from client apps.
This ensures that the logged in users have valid sessions.

Added verifySession middleware to app.js

---

lib/app.js

Securing the sync requests with session validation.

Added session authentication to sync

---

lib/app.js
npm-shrinkwrap.json
package.json

Mongodb session storage had a wrong default configuration

[Raincatch 510] Fix mongodb storage

---

.travis.yml
lib/app.js
npm-shrinkwrap.json
package.json

This is the feature branch for the session management functionality.

Feature branch for session storage

---

npm-shrinkwrap.json
package.json

Removed alpha version, kept version inline with other demo apps for the release (after previous accidental merge of an alpha version into master). Regenerated shrinkwrap.

version change, regenerate shrinkwrap

---

lib/app.js

Development is broken without this change.
Review @vchepeli @paolobueno @emilioicai

Fix missing require for admin router

---

lib/app.js

Allow to see uploaded files (add security exception)
More work to be done as: https://issues.jboss.org/browse/RAINCATCH-576
review @witmicko @austincunningham @damienomurchu

Raincatch-118 - Security exception for files endpoint.

---

npm-shrinkwrap.json
package.json

version bump

---

lib/app.js
lib/data_collision_handlers/globalHandler.js
npm-shrinkwrap.json
package.json

Developers should be able to add their own collision handlers for the raincatcher-sync module.
allowed a custom handler to be added to sync options for a dataset, using fh-mbaas-api sync functionality to set custom collision handler
https://github.com/feedhenry-raincatcher/raincatcher-sync/pull/24
https://issues.jboss.org/browse/RAINCATCH-219

RAINCATCH-219 Added user-defined collision handlers

---

package.json
sonar-project.properties

bumping for user fix
@vchepeli @TommyJ1994

fh-* version bumps

---

README.md

Adding mongo line

---

Gruntfile.js

When running on cluster we should use default connection

Use default connection by default

---

package.json

RAINCATCH-748  - update mongoose module version

---

package.json

Related to https://github.com/feedhenry-raincatcher/raincatcher-mongoose-store/pull/13

Bump fh-wfm-mongoose-store

---

application.js
lib/app/group.js
lib/app/message.js
lib/app/result.js
lib/app/workflow.js
lib/app/workorder.js
package.json

If the application setup encounters an error, it should be logged and the app should not start.
Related to https://github.com/feedhenry-raincatcher/raincatcher-mongoose-store/pull/16

Handling errors setting up test data

---

README.md

 ## Running The Demo Solution Locally

---

README.md

Past = conjonction
Presence = conjunction

RHMAP-13751 raincatcher-demo-cloud
